version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: passwordPsite
      DATABASE_NAME: psiteDB
    volumes:
      - .:/usr/src/app
    # Pour le développement, vous pouvez utiliser start:dev
    command: yarn start:dev

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwordPsite
      POSTGRES_DB: psiteDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: